### ISSUE TITLE
backend firebase coms

### ISSUE THREAD

**Issue by RicardoGuevara** [wecode4food/lilith#8]

**Comment by RicardoGuevara** [comment]
// estructura de registro de nuevos usuarios

cons.webSocket.emit('register', 
    {
      cc: "1002971433",
      nombre: "Ricardo Guevara",
      email: "ricardoguevarapayan@gmail.com",
      password: "123456",
      barrio: "villa mojon"
    });

**Comment by RicardoGuevara** [comment]
// estructura de login comun

cons.webSocket.emit('login', 
    {
      email: "ricardoguevarapayan@gmail.com",
      password: "123456"
    });

**Comment by RicardoGuevara** [comment]
//registro
cons.webSocket.emit('register',
    {
    admin: false,
    cc: "123456789",
    nombre: "ste men",
    email: "ggg@ggg.com",
    password: "123456",
    barrio: "un sitio"
    });

**Comment by AlguienMore** [comment]
Leer datos de firebase:
firebase.database().ref('Ruta').on("value", snapshot => {
            objetoConLosDatos= snapshot.val(); //siempre es snapshot.val() para tomar el json de la ruta
            console.log(snapshot.val());//esto es para mostrar
});

**Comment by RicardoGuevara** [comment]
cons.webSocket.emit('read',
    {
      child: 'usuarios',
    });

**Comment by RicardoGuevara** [comment]
cons.webSocket.on('connection',function(s){
      s.on('result',(resultado) => {
        this.lastResult = resultado;
      });
    });
